<?xml version="1.0" encoding="UTF-8"?><testsuite failures="1" name="cucumber.runtime.formatter.JUnitFormatter" skipped="0" tests="1" time="88.720647">
<testcase classname="Login" name="Login with invalid credentials" time="88.720647">
<failure message="java.lang.AssertionError&#13;&#10;&#9;at org.junit.Assert.fail(Assert.java:86)&#13;&#10;&#9;at org.junit.Assert.assertTrue(Assert.java:41)&#13;&#10;&#9;at org.junit.Assert.assertTrue(Assert.java:52)&#13;&#10;&#9;at pageObjects.SignInPage.verifyErrorMessag(SignInPage.java:251)&#13;&#10;&#9;at stepDefinitions.LoginSteps.error_message_appear(LoginSteps.java:29)&#13;&#10;&#9;at ✽.Then Error message appear(login.feature:7)&#13;&#10;"><![CDATA[Given User is in login page.................................................passed
When Enter invalid email and password.......................................passed
Then Error message appear...................................................failed

StackTrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at pageObjects.SignInPage.verifyErrorMessag(SignInPage.java:251)
	at stepDefinitions.LoginSteps.error_message_appear(LoginSteps.java:29)
	at ✽.Then Error message appear(login.feature:7)
]]></failure>
</testcase>
</testsuite>
